

services:
  gestorinventario:
    container_name: gestor-inventario
    image: ${DOCKER_REGISTRY-}gestorinventario
    build:
      context: .
      dockerfile: Dockerfile

    ports:
     
      - "8080:8080"
      - "8081:8081"
     
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_SA_PASSWORD=${DB_SA_PASSWORD}
      - IS_DOCKER=true
      - USE_REDIS=true 
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/GestorInventario.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ClaveJWT=${ClaveJWT}
      - REDIS_CONNECTION_STRING=${REDIS_CONNECTION_STRING} 
      - JwtIssuer=${JwtIssuer}
      - JwtAudience=${JwtAudience}
      - PublicKey=${PublicKey}
      - PrivateKey=${PrivateKey} 
      - DB_USERNAME=${DB_USERNAME} 
      - Paypal_ClientId=${Paypal_ClientId}
      - Paypal_ClientSecret=${Paypal_ClientSecret}
      - Paypal_Mode=${Paypal_Mode}
      - Paypal_returnUrlConDocker=${Paypal_returnUrlConDocker}
      - Paypal_returnUrlSinDocker=${Paypal_returnUrlSinDocker} 
      - Email__Host=${Email__Host}
      - Email__Port=${Email__Port}
      - Email__Username=${Email__Username}
      - Email__Password=${Email__Password} 

    volumes:
       - C:/Users/guill/AppData/Roaming/ASP.NET/Https/GestorInventario.pfx:/https/GestorInventario.pfx:ro
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  appdata:
    driver: local
  redisdata:
    driver: local
