version: '3.4'

networks:
  gestorInventarionetwork:

services:
  gestorInventariodb:
    container_name: app-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "8002:1433"
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd12345
    networks:
      - gestorInventarionetwork

  gestorinventario:
    container_name: gestor-inventario
    image: ${DOCKER_REGISTRY-}gestorinventario
    build:
      context: .
      dockerfile: GestorInventario/Dockerfile
    ports:
      - "8001:80"
    depends_on:
      - gestorInventariodb
    environment:
      - DB_HOST=gestorInventariodb
      - DB_NAME=GestorInventario
      - DB_SA_PASSWORD=P@ssw0rd12345
      - IS_DOCKER=true
    networks:
      - gestorInventarionetwork
